---
# tasks file for ph.install-appdynamics-machine-agents

- name: check for previous versions of the machine agent
  include: check_for_previous_agents.yml

- name: remove previous versions of the machine agent
  include: remove_machine_agents.yml

- name: prepare for the new machine agent install
  include: prepare_machine_agent.yml

- name: install the machine agent
  include: install_machine_agent.yml

- name: configure the machine agent
  include: configure_machine_agent.yml

- name: start and enable the machine agent
  include: start_machine_agent.yml
