---

- name: stop the machine agent service
  service:
    name: appdynamics-machine-agent
    state: stopped
  ignore_errors: true

- name: remove the rpm, if installed
  command: rpm -e {{ machine_agent_status.stdout }}
  when: previous_agent|bool

- name: remove the existing machine-agent directory
  file:
    state: absent
    path: /opt/appdynamics/machine-agent

...
